### ISSUE TITLE
Name conflict with "tag"

### ISSUE THREAD

**Issue by Alireza-Farahani** [django-crispy-forms/crispy-bootstrap5#91] opened 2022-01-08 09:27 UTC
I have a model "Tag" in my Django app. I tried to used crispy-bootstrap5 for its `CreateView` and `UpdateView` but I was seeing weird behavior on my form result. It got html tags with my "Tag" title! Something like 
```html
<SampleTag>
    ... actual correct form fields
</SampleTag>
```
I debugged it and found that the cause lies in `field.html` template.
```html
<{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_...
```
I can change my `context_object_name` to something else but I think "tag" is a very common name and the library should use some prefixing in its context variables like "bs_tag" or "crispy_tag" to avoid conflict.

**Comment by smithdc1** [comment] 2022-03-09 21:11
Thanks for the report. 

I'm going to close as a duplicate of an issue in the core package as likely it needs fixing there. 

https://github.com/django-crispy-forms/django-crispy-forms/issues/830

**Closed by smithdc1** 2022-03-09 21:11 UTC
